# Generated by Django 4.2 on 2023-05-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(default='SOME STRING', max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('logged', models.BooleanField(default=False)),
                ('superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
