# Generated by Django 4.2 on 2023-05-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.BigIntegerField(default='845305'),
        ),
    ]
