# Generated by Django 4.2 on 2023-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
