# Generated by Django 4.2 on 2023-05-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubCategory', '0001_initial'),
        ('Category', '0001_initial'),
        ('Product', '0002_remove_products_category_remove_products_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Category.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SubCategory.subcategory'),
        ),
    ]
